FIX in auth check - throwable was thrown. TURN password init works. Logging.
* NoClassDefFoundError inherits Object -> Throwable -> Error. Exception catch block does not catch this.
* Cause - exception in private static final field initialization leads to cNoClassDefFoundError.
* Logs refactored, hibernate logs to a separate log file. Warning, info, debug log files separated.